/// Flutter icons Custom
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'Custom';
  static const String _kFontPkg = 'komodo_ui_kit';

  static const IconData fiatIconCircle =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
